# Remove the "version: '3.9'" line from docker-compose.yml
services:
  scraper:
    build: .
    image: gg-scraper:latest
    container_name: gg_scraper
    environment:
      - INTERVAL=600
      - MAX_TS_COLUMNS=8000
      - DB_PATH=/data/ggpoker_leaderboards.db
      - CHROME_BIN=/usr/bin/chromium
      - CHROME_TYPE=chromium
    volumes:
      - ./data:/data
    restart: unless-stopped

  api:
    build: .
    image: gg-api:latest
    container_name: gg_api
    command: python api.py
    environment:
      # Prefer private DB URL if available; fallback to DATABASE_URL or public
      - DATABASE_PRIVATE_URL=${DATABASE_PRIVATE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PUBLIC_URL=${DATABASE_PUBLIC_URL}
      - PORT=8000
    ports:
      - "8000:8000"
    restart: unless-stopped