# Remove the "version: '3.9'" line from docker-compose.yml
services:
  scraper:
    build: .
    image: gg-scraper:latest
    container_name: gg_scraper
    environment:
      - INTERVAL=600
      - MAX_TS_COLUMNS=8000
      - DB_PATH=/data/ggpoker_leaderboards.db
      - CHROME_BIN=/usr/bin/chromium
      - CHROME_TYPE=chromium
    volumes:
      - ./data:/data
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: gg-web:latest
    container_name: gg_web
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    restart: unless-stopped